# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70535fa6b10012edb54b4e79dc7016222ecc2d3731a4a0e026eb10356245edc596b2c3d21980df80cd5e1639da8a6a99759c575aa15978126ad197fe4dfd039e

test:
  secret_key_base: 603f93faf5718c714aa37fe97edc25ef5d78bf9d38d953d3ee46b12d29820ddd7e93edbee7987c44886bfe4988ec278a897bb28e4b69d5673fcde473508bf3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
